services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
    mysql:
        container_name: ${APP_NAME}_mysql
        image: mysql:8.0
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password --disable-log-bin
        tty: true
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
            - "5173:5173"
    cache:
        container_name: ${APP_NAME}_cache
        image: redis:7.0-alpine
        restart: unless-stopped
        ports:
            - '6379:6379'
    phpmyadmin:
        depends_on:
            - mysql
            - php
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}_pma
        restart: unless-stopped
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 100G
        volumes:
            - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini